#!/bin/sh
alias autoremove='sudo pacman -Rns $(pacman -Qtdq) --noconfirm 2>/dev/null || echo "No orphaned packages"'
pacins() { paru -Slq | fzf -m --preview "cat <(paru -Si {1}) <(paru -Fl {1} | awk '{print $2}')" | xargs -ro paru -S; }
pacrem() { paru -Qq | fzf -m --preview "cat <(paru -Si {1}) <(paru -Fl {1} | awk '{print $2}')" | xargs -ro paru -Runs; }

alias grep='grep --color=auto'
alias ls='exa'
alias tree='exa -T'

alias ghc='ghc -no-keep-o-files -no-keep-hi-files'
pascal(){ fpc -Co -Cr -Miso -gl "$1" && rm "${1%.*}".o; }

alias yt-playlist="youtube-dl -o '%(title)s - %(uploader)s (%upload_date)s).%(ext)s'"
alias yt-video="youtube-dl -o '%(title)s - %(uploader)s (%(upload_date)s).%(ext)s' --merge-output-format mkv --write-thumbnail"

bindkey "\e[3~" delete-char
